version: '3.8'

services:
  jizai-app:
    build:
      context: .
      dockerfile: Dockerfile
      # ビルド時の引数として渡す
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    container_name: jizai-app
    ports:
      - "3005:3001"  # ホストの3005ポートをコンテナの3001ポートにマッピング
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
      - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
      - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
    command: sh -c 'printenv | grep ^VITE_ > .env.docker.local && npm run dev -- --mode docker --host 0.0.0.0 --port 3001'
    stdin_open: true
    tty: true