name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (root)
        run: npm ci || npm install
      - name: Typecheck (no emit)
        run: npx tsc -p . --noEmit
      - name: Build
        run: npm run build

  backend-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps (backend)
        working-directory: backend
        run: npm ci || npm install
      - name: Preflight (non-blocking)
        working-directory: backend
        run: npm run preflight || true

