name: Security Audit

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 3 * * 1' # Every Monday 03:00 UTC

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workdir: ['.', 'backend']
    defaults:
      run:
        working-directory: ${{ matrix.workdir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm ci || npm install
      - name: Audit for high+ vulnerabilities
        run: |
          npm audit --audit-level=high
      - name: List outdated (non-blocking)
        run: |
          npm outdated || true

